server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        connection-test-query: select 1
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: RbacHikariCP

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.csk.rbac.system.model

# 通用 mapper插件配置
mapper:
  mappers: com.csk.rbac.common.dao.BaseMapper
  not-empty: false
  identity: mysql

#rbac-security 常量配置
rbac:
  # 登录路径
  login-url: /login
  # 免认证静态资源路径
  anon-resources-url: /css/**,/js/**,/fonts/**,/img/**
  # 验证码相关
  code:
    length: 6
    expireIn: 60
    width: 148
    height: 36
    create-url: /image/code
    login-processing-url: /form/login


